### ISSUE TITLE
Can ActiveSpanSource accept SpanContext (if Spans aren't readily available)

### ISSUE THREAD

**Issue by jjmonzon** [opentracing-contrib/java-grpc#12]
The ClientTracingInterceptor uses the ActiveSpanSource to determine the parent span and ultimately uses it to build a new span as child of the parent. If it's only being used in that fashion, then a SpanContext is sufficient enough to build the span (the code doesn't actually need to use the full Span object).

We find that in our distributed system with different instrumentation implementations, the Span is not readily available for example in an HTTPServletRequest but the SpanContext is. Is there a way to allow us to all the ActiveSpanSource to return a SpanContext instead of a Span?

**Comment by tedsuo** [comment]
Hi @jjmonzon, thanks for opening an issue.

I'm surprised you would extract a SpanContext from HTTPServletRequest, but not  create a span before making outbound calls. Could you describe that situation more?

`ActiveSpanSource` should remain for backwards compatibility reasons. But an alternate `SpanContextSource` interface could be added, and the builder could accept either by adding a `withSpanContextSource` method. So it's possible to add this without creating a breaking change.

The only downside is complexity. The situation where a user calls both `withActiveSpanSource` and `withSpanContextSource` on the builder would need to be resolved. The builder does not currently throw exceptions. 

So, if you could explain more about how this is an issue for you (having only a SpanContext available when making an outbound call feels unexpected) it would be helpful to justify the added complexity. 

Cheers,
-Ted

**Comment by jjmonzon** [comment]
Hi @tedsuo 
Thanks for the response. Our application uses tomcat servlets and we are using another opentracing library (https://github.com/opentracing-contrib/java-web-servlet-filter) to create spans automatically via a ServletContextListener. In our servlet, we make a grpc call using a grpc client and we use your library to do so. The main challenge we have is how to get an active span in order for us to create our ClientTracingInterceptor. The only hook we have for the active span generated by the HTTPServletRequest through tomcat is via a SpanContext (which is injected in the HTTPServletRequest object) . We have gotten around this by creating a new span which is a child of this span which we then pass in to the ClientTracingInterceptor. We would like to be able to avoid creating additional spans and if we have a way to specify the active span context to pass in to the ClientTracingInterceptor that would be great.

**Comment by jjmonzon** [comment]
That will resolve our issue. Thanks!

**Comment by malafeev** [comment]
fixed in version `0.0.6`
