### ISSUE TITLE
Update to gRPC 1.15.0

### ISSUE THREAD

**Issue by pkwarren** [opentracing-contrib/java-grpc#18]
Would it be possible to update this library to compile against gRPC 1.15.0 (or later)? 1.15.0 has moved to Java 7, so then it would be possible to use Java 7 features in this library (diamond operator, try-with-resources).

Also, I noticed that the generated protobuf code used in this project is compiled with a very old version of gRPC (0.15.0) that gives deprecation warnings when compiled with a newer gRPC library. Would it be possible to update the generated code to use a newer version of the protoc generated code or update the project to use protobuf-maven-plugin to generate code as part of the build?

I have a branch here with the suggested changes (https://github.com/opentracing-contrib/java-grpc/compare/master...pkwarren:update_grpc_1.15?expand=1) but wanted to run this by the maintainers first before raising a PR.

**Comment by malafeev** [comment]
@pkwarren please submit PR, your proposal looks good.
