### ISSUE TITLE
Similarity to github::grpc-ecosystem:grpc-opentracing

### ISSUE THREAD

**Issue by nevi-me** [opentracing-contrib/java-grpc#2]
Hi, 

Does this library perform the same functions as [https://github.com/grpc-ecosystem/grpc-opentracing](https://github.com/grpc-ecosystem/grpc-opentracing)?

They follow the same namespace `io.opentracing.contrib` on Maven, so that confused me at first.

**Comment by malafeev** [comment]
We decided to move it here, because of lack of support in grpc-ecosystem. 
So Pull Requests, Issues are welcome here :)
