### ISSUE TITLE
Add standard tags to Spans?

### ISSUE THREAD

**Issue by pkwarren** [opentracing-contrib/java-grpc#22]
There are some tags which seem like they'd be useful to expose out of the box with the default interceptors, including:

* kind: client/server
* component: grpc-java
* grpc.status: Status.getCode().name()
* error: true (if status.isOk() returns false)

What is your feeling on adding some of these tags to the Spans created by opentracing-grpc? Should this be provided for all consumers (for consistent instrumentation) or added by consumers using the span decorator interfaces?

**Comment by malafeev** [comment]
I think standard tags should be added for all consumers.
#23 can also be fixed here
