### ISSUE TITLE
Support setting peer address on server spans

### ISSUE THREAD

**Issue by pkwarren** [opentracing-contrib/java-grpc#23]
It would be useful to expose the remote client's peer address (set in Grpc.TRANSPORT_ADDR_REMOTE_ADDR) as an attribute in the server interceptor.

From https://opentracing.io/specification/conventions/:

> peer.address | string | Remote “address”, suitable for use in a networking client library. This may be a "ip:port", a bare "hostname", a FQDN, or even a JDBC substring like "mysql://prod-db:3306"
> -- | -- | --

**Comment by malafeev** [comment]
good idea, I think it can be part of #22

**Comment by malafeev** [comment]
@pkwarren will you create a PR for this issue?
There are several changes are not released. Should I wait it?
