### ISSUE TITLE
Client span tag "grpc.authority" is not set when authority is not set at call-level

### ISSUE THREAD

**Issue by epkugelmass** [opentracing-contrib/java-grpc#38]
GRPC-Java has two ways of setting the authority for a call, at the Channel level or at the individual call level. This allows for overriding the Channel-level authority per-call. See https://github.com/grpc/grpc-java/blob/master/api/src/main/java/io/grpc/CallOptions.java#L81 and https://github.com/grpc/grpc-java/blob/master/core/src/main/java/io/grpc/internal/CallCredentialsApplyingTransportFactory.java#L98.

The OpenTracing Java GRPC library does not respect this hierarchy/fallback behavior. Instead, only the call-level authority is checked. In most applications, this value will not be set. Like the GRPC-Java library, OpenTracing should then fall back to the channel level value.

**Comment by epkugelmass** [comment]
Pull Request: https://github.com/opentracing-contrib/java-grpc/pull/39

**Comment by malafeev** [comment]
#30 merged
version 0.1.2 released
