### ISSUE TITLE
Possible to add tags in the interceptor?

### ISSUE THREAD

**Issue by vegarsti** [opentracing-contrib/java-grpc#42]
Thanks for this library! I'm trying to set up tracing on a gRPC server now, written in Scala.
I have several tags I would like to add to all endpoints, e.g. the id of the tenant using the service.
Is there a way I can do so in the inteceptor? From what I can gather, to do so one needs to create a span first. I apologize if this is too little information, I'm quite new to tracing.

**Comment by malafeev** [comment]
@vegarsti please look at decorators: https://github.com/opentracing-contrib/java-grpc#custom-span-decorators

**Comment by vegarsti** [comment]
Oh, thanks a lot! Sorry for not reading thoroughly!
