### ISSUE TITLE
Consider reverting change to use NoopTracer if GlobalTracer not registered

### ISSUE THREAD

**Issue by pkwarren** [opentracing-contrib/java-grpc#54]
https://github.com/opentracing-contrib/java-grpc/blob/06b092ef2e2f48e0359307b3045e4306a3eeff15/src/main/java/io/opentracing/contrib/grpc/TracingClientInterceptor.java#L345

This change in the client/server interceptor broke usage in our gRPC apps as the GlobalTracer is registered lazily after the interceptors are created. The old builder would use `GlobalTracer.get()` as the default tracer, which would work once the global tracer was registered. The new behavior will use a NoopTracer and setting the GlobalTracer after creating a client/server interceptor will have no effect.

**Comment by baharclerode** [comment]
The `GlobalTracer` already behaves as per `NoopTracer` when a tracer is not registered with it: 

https://github.com/opentracing/opentracing-java/blob/master/opentracing-util/src/main/java/io/opentracing/util/GlobalTracer.java#L67

The interceptor shouldn't need to duplicate this logic, and just using `GlobalTracer.get()` to initialize the builder should provide better default behavior without breaking any existing usage.

**Comment by malafeev** [comment]
fixed
