### ISSUE TITLE
Server Interceptor Closing Active Span

### ISSUE THREAD

**Issue by nevi-me** [opentracing-contrib/java-grpc#8]
I have created a test project: https://github.com/nevi-me/opentracing-grpc-test where I intercept both the client and the server.

After intercepting the server, the active span is closed, meaning that any other traces that should belong to the current span end up going to different spans.

If you run the above project, you'll see a null value being printed to the console when there should be an active span. The relevant piece of code is here: https://github.com/nevi-me/opentracing-grpc-test/blob/master/src/main/java/me/nevi/opentracingtest/rpc/RouteGuideServer.kt#L80.

I was expecting the current span to be active, so that any more messages that I log get included into the trace.

**Comment by malafeev** [comment]
I found a problem and will fix soon.

**Comment by nevi-me** [comment]
Thanks @malafeev, I can confirm getting spans now. There's another thing that I noticed over the weekend, but I'll make that a separate issue as it might just be a documentation thing (which I'd be able to fix with a PR).

**Comment by malafeev** [comment]
ok, so closing now. fix will be available in 0.0.5 release soon.
